# fly.toml app configuration file generated for marvinhsu-zero-to-production-website on 2023-08-15T21:51:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "marvinhsu-zero-to-production-website"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
