# fly.toml app configuration file generated for zero-to-product on 2023-06-14T00:06:42+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zero-to-product"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
