//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

use super::sea_orm_active_enums::SubscriptionStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subscriptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub name: String,
    pub subscribed_at: DateTimeWithTimeZone,
    pub status: SubscriptionStatus,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::subscription_tokens::Entity")]
    SubscriptionTokens,
}

impl Related<super::subscription_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
