application:
  port: 3000
  logging_levels:
    - "zero_to_production=debug"
    - "tower_http=debug"
    - "axum::rejection=trace"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "marvinhsu_zero_to_production"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  bear_token: "my-secret-token"
  timeout_milliseconds: 10000
