application:
  port: 3000
  base_url: "http://localhost:3000/"
  logging_levels:
    - "zero_to_production=debug"
    - "tower_http=debug"
    - "axum::rejection=trace"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "marvinhsu_zero_to_production"
email_client:
  base_url: "https://api.smtp2go.com/"
  sender_email: "n26064074@gs.ncku.edu.tw"
  api_key: "test_key"
  timeout_milliseconds: 10000
