application:
  port: 3000
  logging_levels:
    - "zero_to_production=debug"
    - "tower_http=debug"
    - "axum::rejection=trace"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "marvinhsu_zero_to_production"
