application:
  port: 3000
  base_url: "http://localhost:3000/"
  logging_levels:
    - "zero_to_production=debug"
    - "tower_http=debug"
    - "axum::rejection=trace"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "marvinhsu_zero_to_production"
email_client:
  base_url: "http://localhost:5000"
  sender_email: "test@gmail.com"
  api_key: "test_key"
  timeout_milliseconds: 10000
jwt_handler:
  private_key: "test_key"
  public_key: "test_key"
  expiration_minutes: 30
redis:
  username: ""
  password: ""
  host: "localhost"
  port: 6379
