database:
  host: "marvinhsu-postgres.flycast"
  port: 5432
  username: "marvinhsu_zero_to_production"
  database_name: "marvinhsu_zero_to_production"
email_client:
  base_url: "https://api.sendgrid.com/"
  sender_email: "n26064074@gs.ncku.edu.tw"