application:
  base_url: "https://marvinhsu-zero-to-production.fly.dev/"
  cors_base_url:
    - "https://marvinhsu-zero-to-production-website.fly.dev"
    - "https://marvinhsu-zero-to-production-website.fly.dev/"
database:
  host: "marvinhsu-postgres.flycast"
  port: 5432
  username: "marvinhsu_zero_to_production"
  database_name: "marvinhsu_zero_to_production"
email_client:
  base_url: "https://api.smtp2go.com/"
  sender_email: "n26064074@gs.ncku.edu.tw"