name: Deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install pytest and requests
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
      - name: Build Dockerfile and run image
        run: |
          docker build -t fly-python .
          docker run -p 3000:3000 myapp
      - name: Run tests
        run: |
          poetry run pytest
  deploy:
    name: Deploy app
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}