name: frontend deploy
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_FRONTEND_DEPLOY_TOKEN }}
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            cd ./frontend
            flyctl deploy --remote-only
