name: frontend deploy
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_FRONTEND_DEPLOY_TOKEN }}
      steps:
        - uses: actions/checkout@v3
        - run: cd frontend/
        - run: pwd
        - run: ls
#        - uses: superfly/flyctl-actions/setup-flyctl@master
#        - run: flyctl deploy --remote-only